name: chat_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  #firebase
  cloud_firestore: ^4.0.4
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1

  cupertino_icons: ^1.0.2

  #bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  #equatable
  equatable: ^2.0.5
  
  #get_it
  get_it: ^7.2.0
  
  #dio
  dio: ^4.0.6

  #dartz
  dartz: ^0.10.1

  flutter:
    sdk: flutter

  #screen_utils
  flutter_screenutil: ^5.6.0

  #save_to_gallery
  gallery_saver: ^2.3.2

  #path_provider
  path_provider: ^2.0.11

  #voice_message
  voice_message_package: ^0.0.74

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
 